# # services:
# #   db:
# #     image: postgres:17.4
# #     restart: always
# #     environment:
# #       POSTGRES_USER: saqibw2
# #       POSTGRES_PASSWORD: saqibwani
# #       POSTGRES_DB: auth_session_db_postgres
# #     ports:
# #       - 5432:5432
# #     volumes:
# #       - db_data:/var/lib/postgresql/data
# # volumes:
# #   db_data:
# services:
#   postgres:
#     image: postgres:17.4
#     ports:
#       - 8080:8080
#     environment:
#       POSTGRES_USER: saqibw2
#       POSTGRES_PASSWORD: saqibwani
#       POSTGRES_DB: auth_session_db_postgres
services:
  postgres:
    image: postgres:17.4
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: SAQIBDEV
      POSTGRES_PASSWORD: SAQIBWANI1
      POSTGRES_DB: auth_session_db_postgres
