services:
  postgres:
    image: postgres:17.4
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: SAQIBDEV
      POSTGRES_PASSWORD: process.env.DATABASE_PASSWORD
      POSTGRES_DB: auth_session_db_postgres
